CREATE TABLE "news" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"title" TEXT NOT NULL DEFAULT(''),
	"text" TEXT NOT NULL DEFAULT(''),
	"author" TEXT NOT NULL DEFAULT(''),
	"postedon" INTEGER NOT NULL DEFAULT(0),
	"editon" INTEGER NOT NULL DEFAULT(0)
);

CREATE TABLE captcha (
    "id" TEXT UNIQUE NOT NULL,
    "equation" TEXT UNIQUE NOT NULL,
    "result" INTEGER UNIQUE NOT NULL,
    "createdon" INTEGER NOT NULL,
	PRIMARY KEY ("id", ASC)
);

