CREATE TABLE "news" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"title" TEXT NOT NULL DEFAULT(''),
	"text" TEXT NOT NULL DEFAULT(''),
	"author" TEXT NOT NULL DEFAULT(''),
	"postedon" INTEGER NOT NULL DEFAULT(0),
	"editon" INTEGER NOT NULL DEFAULT(0)
);
/*
CREATE TABLE "comments" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"newsId" INTEGER NOT NULL DEFAULT(0),
	"parentId" INTEGER NULL DEFAULT null,
	"text" TEXT NOT NULL DEFAULT(''),
	"author" TEXT NOT NULL DEFAULT(''),
	"postedon" TEXT NOT NULL DEFAULT(''),
	"status" INTEGER NOT NULL DEFAULT(1)
);*/
